// Curated stock photo URLs. The per-dish mapping lives in dish-images.json,
// generated by scripts/fetch-dish-images.ts which queries:
//   - TheMealDB (free Indian-food image CDN, ~32 of our 81 dishes)
//   - Foodish API (random food images per category, ~41 of our dishes)
//   - Hand-curated Unsplash URLs (8 specific overrides for beverages, etc.)
//
// To replace any of these with a real photoshoot:
//   1. Upload your image to S3 / R2 / etc.
//   2. Set Item.imageUrl in the admin/menu panel — it overrides this table.
//
// Re-run the fetcher whenever menu items change:
//   $env:DATABASE_URL = "file:./apps/api/prisma/dev.db"
//   npx tsx scripts/fetch-dish-images.ts

import dishImages from './dish-images.json';

const us = (id: string, w = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;
const food = (cat: string, n: number) =>
  `https://foodish-api.com/images/${cat}/${cat}${n}.jpg`;

// Hero / marketing — verified live at the time of writing.
export const HERO       = us('photo-1633945274405-b6c8069047b0', 1800);
export const STORY      = us('photo-1599043513900-ed6fe01d3833', 1400);
export const SPICES     = us('photo-1532336414038-cf19250c5757', 1200);
export const TANDOOR    = us('photo-1631452180519-c014fe946bc7', 1200);
export const RESTAURANT = us('photo-1592861956120-e524fc739696', 1600);

const CATEGORY_PHOTOS: Record<string, string> = {
  Biryani:                food('biryani', 1),
  'Biryani — Non-Veg':    food('biryani', 1),
  'Biryani — Veg':        food('biryani', 4),
  'Family Packs & Combos': food('biryani', 3),
  'Hyderabadi Specials':  food('butter-chicken', 1),
  'Starters — Non-Veg':   food('butter-chicken', 2),
  'Starters — Veg':       food('butter-chicken', 3),
  'Tandoor & Kebabs':     food('butter-chicken', 4),
  'Curries — Non-Veg':    food('butter-chicken', 5),
  'Curries — Veg':        food('butter-chicken', 4),
  'Indo-Chinese':         food('rice', 1),
  'Breads & Rice':        food('butter-chicken', 2),
  Desserts:               food('dessert', 1),
  Beverages:              '',
};

type ImageRecord = { url: string; source: 'mealdb' | 'foodish' | 'manual' | 'none' };
const map = dishImages as unknown as Record<string, ImageRecord>;

export function dishPhoto(name: string, category?: string, fallback?: string | null) {
  if (fallback) return fallback;
  const entry = map[name];
  if (entry?.url) return entry.url;
  if (category && CATEGORY_PHOTOS[category]) return CATEGORY_PHOTOS[category];
  return ''; // <DishImage> renders the gradient + emoji placeholder
}
